### ISSUE TITLE
Benefit Administration

### ISSUE THREAD

**Issue by James1x0** [associatedemployers/granite#554]
## Generic benefits
- [ ] Ability to administer generic benefits like parking, gyms, etc.

## Other
- [ ] Life & disability
- [ ] 401k/IRA/Simple enrollment
- [ ] FSA and HSA accounts
- [ ] Supplemental benefits

## Enrollment Ideas
- Month/pay-period cost view

## Administration Ideas

**Comment by James1x0** [comment]
Landed MVP. Closing epic and moving issues to a main workflow.
