### ISSUE TITLE
[Feature] Supervisor tracking

### ISSUE THREAD

**Issue by James1x0** [associatedemployers/granite#65]
- [ ] Add selection in employee onboarding
- [ ] display in employee information
- [ ] display all `supervises` in employee information
